version: '3'

services:
  app:
    build:
      context: .
      args:
        VARIANT: '3.1-bullseye'
        BUNDLER_VERSION: '2.3.14'
        RAILS_VERSIONS: '7.0.3'
        NODE_VERSION: '16'
    environment:
      BINDING: 0.0.0.0
      DATABASE_HOST: db
    volumes:
      - ..:/home/vscode/environment:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - '3000:3000'  # Rails用のポート3000を外部に公開
    depends_on:
      - db
    command: rails server -b 0.0.0.0 -p 3000  # Railsサーバーの起動

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'  # MySQLのデフォルトポート3306を公開
    volumes:
      - db-data:/var/lib/mysql
volumes:
  bundle-volume:
  db-data:
